# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a31d49315452fcdd587a67cb7bf2511d80619460b40aa74a6ada1c9e124f122aa107aa490c657845fc627b393a71a3da2c80ba27d8f8ec805f71ac20042d79b

test:
  secret_key_base: e5a313c4a111a192b19f3674815d3546a7390fb5c1ef737f5d7e53fd2ed2593950514eed71c936efba24c3d2fef4228976492200216e5de89df5ca141eae02e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
